Update styles.css в LK
Proffet78/KR_TRPO_Modern pull request #43
Opened 2020-07-01 06:18 UTC by VinogradovAlexandr781227

Closes- #19

2020-07-01 17:11 UTC, Proffet78 requested changes
не могу засчитать комит, так как ничего не добавлено

2020-07-01 17:12 UTC, Proffet78 commented
Измени цветовую гамму согласно комментариям

2020-07-01 17:19 UTC, Proffet78 commented
Цветовая гамма не соответствует стандарту!

2020-07-01 17:19 UTC, Proffet78 commented
Неверная цветовая палитра!
Цвета:
Красный - 8B0000
Синий - 191970
Серый - 2f2f2f
Темный серый - 222222
Белый - ffffff

ИСПОЛЬЗУЕМ только эти цвета! + подбери красивое сочетание!

2020-07-02 18:00 UTC, VinogradovAlexandr781227 commented
Задача выполнена. Ожидаю проверки выполнения.

2020-07-02 18:26 UTC, Proffet78 approved these changes

2020-07-02 18:27 UTC, Proffet78 commented
Можешь мержить

2020-07-02 19:02 UTC, merged