Авторизация пользователя, добавление новых страниц #76
Proffet78/KR_TRPO_Modern pull request #86
Opened 2020-09-07 19:42 UTC by JennyShel18

#76

2020-09-08 12:23 UTC, ssas18 approved these changes

2020-09-14 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-14 17:46 UTC, YuriSilenok requested changes
Компилируемые файлы в репозитории:
- добавить в .gitignore строку `*.pyc`
- удалить из индексации командой git rm --cached *.pyc

2020-09-14 17:46 UTC, YuriSilenok commented on DJANGO/DJANGO/apps/siteDJ/models.py
> +class UserTwo (models.Model):
Зачем нам два раза сведения о пользователе хранить?

2020-09-15 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-16 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-20 07:23 UTC, ssas18 approved these changes

2020-09-20 19:20 UTC, YuriSilenok requested changes
Выводите из индекса бинарные файлы
- DJANGO/DJANGO/apps/siteDJ/__pycache__/admin.cpython-38.pyc
- DJANGO/DJANGO/apps/siteDJ/__pycache__/models.cpython-38.pyc
- DJANGO/DJANGO/apps/siteDJ/migrations/__pycache__/0001_initial.cpython-38.pyc
- DJANGO/DJANGO/apps/siteDJ/migrations/__pycache__/0002_usertwo.cpython-38.pyc

2020-09-20 22:05 UTC, JennyShel18 commented
Сделано

2020-09-21 13:25 UTC, YuriSilenok approved these changes

2020-09-22 16:17 UTC, ssas18 approved these changes

2020-09-22 17:01 UTC, merged