Исправил баг с масштабированием
Proffet78/KR_TRPO_Modern pull request #87
Opened 2020-09-07 19:55 UTC by VinogradovAlexandr781227

#79

2020-09-08 12:24 UTC, ssas18 requested changes
Ветка должна быть дев)

2020-09-14 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-15 05:02 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-16 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-09-19 21:30 UTC, JennyShel18 requested changes
Мерж должен быть в ветку dev

2025-04-26 13:53 UTC, YuriSilenok commented
Пора закрыть этот запрос

2025-04-26 14:04 UTC, closed without merging